<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomerApp.Application\CustomerApp.Application.csproj" />
    <ProjectReference Include="..\CustomerApp.Infrastructure\CustomerApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
